services:
  mongodb:
    image: mongo:7-jammy
    container_name: omind-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=omind-ai-contact-center
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - omind-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: omind-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/omind-ai-contact-center?authSource=admin
      - JWT_SECRET=omind-ai-super-secret-jwt-key-2024
      - JWT_EXPIRE=7d
      - UPLOAD_DIR=./uploads
      - MAX_FILE_SIZE=50000000
      - LOG_LEVEL=info
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/logs:/usr/src/app/logs
    depends_on:
      - mongodb
    networks:
      - omind-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: omind-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - omind-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local

networks:
  omind-network:
    driver: bridge
